#pragma once

// -----------------------------------------------------------------------------
// THIS FILE IS AUTOGENERATED
// see generate_enum_data.py
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Tribes
// -----------------------------------------------------------------------------

enum class Tribe {
    None,
    Murloc,
    Demon,
    Mech,
    Beast,
    Dragon,
    All,
};

const int TRIBE_COUNT = 7;

// -----------------------------------------------------------------------------
// Minion types
// -----------------------------------------------------------------------------

enum class MinionType : unsigned char {
    None,
    // Tier 1
    Alleycat,
    DireWolfAlpha,
    FiendishServant,
    Mecharoo,
    MicroMachine,
    MurlocTidecaller,
    MurlocTidehunter,
    RighteousProtector,
    RockpoolHunter,
    SelflessHero,
    VulgarHomunculus,
    WrathWeaver,
    // Tier 2
    AnnoyOTron,
    HarvestGolem,
    Imprisoner,
    KaboomBot,
    KindlyGrandmother,
    MetaltoothLeaper,
    MountedRaptor,
    MurlocWarleader,
    NathrezimOverseer,
    OldMurkEye,
    PogoHopper,
    RatPack,
    ScavengingHyena,
    ShieldedMinibot,
    SpawnOfNZoth,
    Zoobot,
    // Tier 3
    CobaltGuardian,
    ColdlightSeer,
    CrowdFavorite,
    Crystalweaver,
    FloatingWatcher,
    Houndmaster,
    ImpGangBoss,
    InfestedWolf,
    Khadgar,
    PackLeader,
    PhalanxCommander,
    PilotedShredder,
    PsychOTron,
    ReplicatingMenace,
    ScrewjankClunker,
    ShifterZerus,
    SoulJuggler,
    TheBeast,
    TortollanShellraiser,
    // Tier 4
    AnnoyOModule,
    BolvarFireblood,
    CaveHydra,
    DefenderOfArgus,
    FesterootHulk,
    IronSensei,
    MechanoEgg,
    MenagerieMagician,
    PilotedSkyGolem,
    SecurityRover,
    Siegebreaker,
    TheBoogeymonster,
    Toxfin,
    VirmenSensei,
    // Tier 5
    AnnihilanBattlemaster,
    BaronRivendare,
    BrannBronzebeard,
    GoldrinnTheGreatWolf,
    IronhideDirehorn,
    Junkbot,
    KingBagurgle,
    LightfangEnforcer,
    MalGanis,
    PrimalfinLookout,
    SatedThreshadon,
    SavannahHighmane,
    StrongshellScavenger,
    Voidlord,
    // Tier 6
    FoeReaper4000,
    GentleMegasaur,
    Ghastcoiler,
    KangorsApprentice,
    Maexxna,
    MamaBear,
    SneedsOldShredder,
    ZappSlywick,
    // Tokens
    Amalgam,
    BigBadWolf,
    DamagedGolem,
    EmperorCobra,
    FinkleEinhorn,
    GuardBot,
    HenchClanSquire,
    Hyena,
    Imp,
    IronhideRunt,
    JoEBot,
    Microbot,
    MurlocScout,
    Plant,
    Primalfin,
    Rat,
    Robosaur,
    Safeguard,
    Snake,
    Spider,
    Tabbycat,
    VaultSafe,
    Voidwalker,
    // Tokens
    AmalgamExplorer,
};

const int MINIONTYPE_COUNT = 108;

// -----------------------------------------------------------------------------
// Heroes and hero powers
// -----------------------------------------------------------------------------

enum class HeroType {
    None,
    AFKay,
    ArchVillainRafaam,
    Bartendotron,
    BrannBronzebeard,
    DancinDeryl,
    EdwinVanCleef,
    EliseStarseeker,
    GeorgeTheFallen,
    Giantfin,
    InfiniteToki,
    KelThuzad,
    KingMukla,
    LichBazhial,
    LordJaraxxus,
    MillhouseManastorm,
    MillificentManastorm,
    Nefarian,
    PatchesThePirate,
    Patchwerk,
    ProfessorPutricide,
    Pyramad,
    QueenWagtoggle,
    RagnarosTheFirelord,
    RenoTheRelicologist,
    Shudderwock,
    Sindragosa,
    SirFinleyMrrgglton,
    SylvanasWindrunner,
    TheCurator,
    TheGreatAkazamzarak,
    TheLichKing,
    TheRatKing,
    TirionFordring,
    TradePrinceGallywix,
    YoggSaronHopesEnd,
};

const int HEROTYPE_COUNT = 36;
