#pragma once

// -----------------------------------------------------------------------------
// THIS FILE IS AUTOGENERATED
// see generate_enum_data.py
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Tribes
// -----------------------------------------------------------------------------

enum class Tribe {
    None,
    Murloc,
    Demon,
    Mech,
    Beast,
    Dragon,
    All,
};

const int TRIBE_COUNT = 7;

// -----------------------------------------------------------------------------
// Minion types
// -----------------------------------------------------------------------------

enum class MinionType : unsigned char {
    None,
    // Tier 1
    Alleycat,
    DireWolfAlpha,
    DragonspawnLieutenant,
    FiendishServant,
    Mecharoo,
    MicroMachine,
    MurlocTidecaller,
    MurlocTidehunter,
    RedWhelp,
    RighteousProtector,
    RockpoolHunter,
    SelflessHero,
    VulgarHomunculus,
    WrathWeaver,
    // Tier 2
    GlyphGuardian,
    HarvestGolem,
    Imprisoner,
    KaboomBot,
    KindlyGrandmother,
    MetaltoothLeaper,
    MurlocWarleader,
    NathrezimOverseer,
    OldMurkEye,
    PogoHopper,
    RatPack,
    ScavengingHyena,
    SpawnOfNZoth,
    StewardOfTime,
    UnstableGhoul,
    WaxriderTogwaggle,
    Zoobot,
    // Tier 3
    BronzeWarden,
    CobaltGuardian,
    ColdlightSeer,
    CrowdFavorite,
    Crystalweaver,
    HangryDragon,
    Houndmaster,
    ImpGangBoss,
    InfestedWolf,
    Khadgar,
    PackLeader,
    PilotedShredder,
    ReplicatingMenace,
    ScrewjankClunker,
    ShifterZerus,
    SoulJuggler,
    TheBeast,
    TwilightEmissary,
    // Tier 4
    AnnoyOModule,
    BolvarFireblood,
    CaveHydra,
    CobaltScalebane,
    DefenderOfArgus,
    DrakonidEnforcer,
    FloatingWatcher,
    HeraldOfFlame,
    IronSensei,
    MechanoEgg,
    MenagerieMagician,
    SavannahHighmane,
    SecurityRover,
    Siegebreaker,
    Toxfin,
    VirmenSensei,
    // Tier 5
    AnnihilanBattlemaster,
    BaronRivendare,
    BrannBronzebeard,
    GoldrinnTheGreatWolf,
    IronhideDirehorn,
    Junkbot,
    KingBagurgle,
    LightfangEnforcer,
    MalGanis,
    Murozond,
    PrimalfinLookout,
    RazorgoreTheUntamed,
    SneedsOldShredder,
    StrongshellScavenger,
    Voidlord,
    // Tier 6
    FoeReaper4000,
    GentleMegasaur,
    Ghastcoiler,
    HolyMackerel,
    ImpMama,
    KalecgosArcaneAspect,
    KangorsApprentice,
    Maexxna,
    MamaBear,
    NadinaTheRed,
    ZappSlywick,
    // Tokens of tier 1
    Amalgam,
    BigBadWolf,
    DamagedGolem,
    EmperorCobra,
    FinkleEinhorn,
    GuardBot,
    HenchClanSquire,
    Hyena,
    Imp,
    IronhideRunt,
    JoEBot,
    Microbot,
    MurlocScout,
    Plant,
    Primalfin,
    Rat,
    Robosaur,
    Safeguard,
    Snake,
    Spider,
    Tabbycat,
    VaultSafe,
    Voidwalker,
    // Tokens of tier 2
    AmalgamExplorer,
    AnnoyOTron,
    MountedRaptor,
    NightmareAmalgam,
    // Tokens of tier 3
    PhalanxCommander,
    PsychOTron,
    TortollanShellraiser,
    // Tokens of tier 4
    FesterootHulk,
    PilotedSkyGolem,
    TheBoogeymonster,
    // Tokens of tier 5
    SatedThreshadon,
    // Custom minion
    ShieldedMinibot,
};

const int MINIONTYPE_COUNT = 127;

// -----------------------------------------------------------------------------
// Heroes and hero powers
// -----------------------------------------------------------------------------

enum class HeroType {
    None,
    AFKay,
    Alexstrasza,
    ArchVillainRafaam,
    Bartendotron,
    DancinDeryl,
    Deathwing,
    DinotamerBrann,
    EdwinVanCleef,
    EliseStarseeker,
    FungalmancerFlurgl,
    Galakrond,
    GeorgeTheFallen,
    Giantfin,
    InfiniteToki,
    KelThuzad,
    KingMukla,
    LichBazhial,
    LordJaraxxus,
    Malygos,
    MillhouseManastorm,
    MillificentManastorm,
    Nefarian,
    Nozdormu,
    PatchesThePirate,
    Patchwerk,
    ProfessorPutricide,
    Pyramad,
    QueenWagtoggle,
    RagnarosTheFirelord,
    RenoJackson,
    Shudderwock,
    Sindragosa,
    SirFinleyMrrgglton,
    SylvanasWindrunner,
    TheCurator,
    TheGreatAkazamzarak,
    TheLichKing,
    TheRatKing,
    TirionFordring,
    TradePrinceGallywix,
    YoggSaronHopesEnd,
    Ysera,
};

const int HEROTYPE_COUNT = 43;
